apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.ovh.playground.dataminded.cloud"
      path: "secrets"
      version: "v2"
      auth:
        # Authenticate against Vault using a Kubernetes ServiceAccount
        # token stored in a Secret.
        # https://www.vaultproject.io/docs/auth/kubernetes
        tokenSecretRef:
          name: "eso-vault-secret"
          key: "token"
          namespace: "services"
        # kubernetes:
        #   # Path where the Kubernetes authentication backend is mounted in Vault
        #   mountPath: "kubernetes"
        #   # A required field containing the Vault Role to assume.
        #   role: "eso-vault-role"
          # Optional service account field containing the name
          # of a kubernetes ServiceAccount
        #   serviceAccountRef:
        #     name: "eso-vault-sa"
